title = "BMauri"
baseURL = "" # "https://maguri.github.io/bmauri-website/"
languageCode = "es-es"
theme = "bmauri-theme"

[menu]

  [[menu.header]]
    weight = 2
    name = "Ingeniería"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Proyectos"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Tecnologías"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contacto"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "Nosotros"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contactanos"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Proyectos"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Inicio"

  [params.slider]
    enable = true
    title = "Te ayudamos a llegar más lejos"
    subtitle = "Pesage industiral, Digitalizamos la industria<br/>Trabajamos de forma cercana con el clilente para dar la mejor solución a sus necesidades."

  [params.wrapper]
    enable = true
    title = "Nosotros"
    italic = "Somos una empresa familiar cercana e íntima con el cliente. Destacamos por la proximidad y la profesionalidad con lo que hacemos las cosas."
    paragraph = "Somos capaces de trabajar en entornos bien diferentes dentro de la industria del pesaje. Trabajamos tanto en la industria del pesaje logístico de transportes y mercaderías, desde el pesage industrial en el sector alimentario y otros, a pesaje a nivel de laboratorio."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Creemos en la perfección"
    content = "Nos satisface el buen trabajo y que el cliente pueda cumplir con sus necesidades de manera ágil y sin interrupciones. Somos profesionales y nos implicamos de forma personal en cada uno de nuestros proyectos. Ya sea trabajando con pequeñas o grandes empresas, gracias a nuestro <strong>Departamento de I+D</strong>, aportamos la mejor solución a las necesidades de esta y le ayudamos a seguir creciendo hacia la buena dirección."
    [params.feature.button]
      caption = "Ver Proyectos"
      url = "/blog"

  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
      action = "https://formspree.io/oriolmauriguiu@hotmail.com"
      thanks_message = "Thanks for your message, we will send you our answer as soon as possible."
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
      iframe = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12020.208693514061!2d1.246716!3d41.133387!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x60c510bdd5f5827c!2sB%C3%A1sculas+Mauri!5e0!3m2!1sen!2ses!4v1530261994131"
