---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: bmauri-website/content/english/blog
  label: Post (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: bmauri-website/content/spanish/blog
  label: Post (es)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: bmauri-website/content/english/author
  label: Author (en)
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: bmauri-website/content/spanish/author
  label: Author (es)
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Project
- type: directory
  path: bmauri-website/content/english/project
  label: Project (en)
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: bmauri-website/content/spanish/project
  label: Project (es)
  create: documents
  match: "**/*"
  templates:
  - project
- type: heading
  label: Others Pages
- type: directory
  path: bmauri-website/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/spanish/about
  label: About (es)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/english/service
  label: Service (en)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/spanish/service
  label: Service (es)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/english/pricing
  label: Pricing (en)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/spanish/pricing
  label: Pricing (es)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/english/faq
  label: FAQ (en)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/spanish/faq
  label: FAQ (es)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/spanish/contact
  label: Contact (es)
  create: none
  match: "*"
- type: directory
  path: bmauri-website/content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: bmauri-website/content/spanish/pages
  label: Created Pages (es)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: bmauri-website/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: bmauri-website/content/spanish
  label: All Pages (es)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: bmauri-website/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: bmauri-website/data/es
  label: Data (es)
  create: all
  match: "**/*"
- type: directory
  path: bmauri-website/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: bmauri-website
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: bmauri-website/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.66.0
  - BUILD_DIR=/srv
  preview_output_directory: public
  install_dependencies_command: git clone --depth 1 https://github.com/maguri/bmauri-theme.git
    $BUILD_DIR/themes/bmauri-theme/
  preview_docker_image: forestryio/hugo:latest
  mount_path: "$BUILD_DIR"
  working_dir: "$BUILD_DIR"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
